version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: janghan
      POSTGRES_PASSWORD: wkd123
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "8080:8080"
      - "5555:5555"
    env_file:
      - server/.env
    depends_on:
      - db

  client:
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  postgres-data:
