version: "3.9"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "8080:8080"
      - "5555:5555"
    env_file:
      - server/.env

  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  postgres-data:
