version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    depends_on:
      - api
      - web
    ports:
      - '80:80'

  api:
    build:
      context: ./server
      target: production
      args:
        - DOCKER_BUILDKIT=1
    environment:
      - NODE_ENV=production
    ports:
      - '9000:9000'
    env_file:
      - server/.env

  web:
    build:
      context: ./client
      target: production
      args:
        - DOCKER_BUILDKIT=1
    environment:
      - NODE_ENV=production
    ports:
      - '80'
    depends_on:
      - api
