version: '3.9'

services:
  nginx:
    image: nginx:1.17.10
    depends_on:
      - api
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'

  web:
    build:
      context: ./client
    environment:
      - NODE_ENV=production
    ports:
      - '80'
    depends_on:
      - api

  api:
    build:
      context: ./server
    environment:
      - NODE_ENV=production
    ports:
      - '9000:9000'
    env_file:
      - server/.env
