version: '3.9'
name: chit-chat-dev

services:
  nginx:
    container_name: nginx-dev
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - api
      - web

  api:
    container_name: api-dev
    build:
      context: ./server
      target: development
      args:
        - DOCKER_BUILDKIT=1
    volumes:
      - /app/node_modules
      - ./server:/app
      - ./cypress/fixtures:/cypress/fixtures
    ports:
      - '9000:9000'
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:54322/postgres

  web:
    container_name: client-dev
    build:
      context: ./client
      target: development
      args:
        - DOCKER_BUILDKIT=1
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    depends_on:
      - api
