# fly.toml file generated for green-sky-362 on 2023-04-17T18:47:12+10:00

app = "green-sky-362"
primary_region = "syd"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
